[package]
name = "blinking-lights"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.3"
microbit-v2 = "0.13.0"
nrf52833-pac = { version = "0.12.2", features = ["rt"] }
panic-halt = "0.2.0"
